In [3]:
try:
    import numpy as np
    # Prueba simple: Crear un array
    test_array = np.array([1, 2, 3])
    print("NumPy está instalado correctamente.")
except ImportError:
    print("NumPy no está instalado. Por favor, instala usando: pip install numpy")
except:
    print("NumPy está instalado pero no está funcionando adecuadamente.")

try:
    import pandas as pd
    # Prueba simple: Crear un DataFrame
    test_df = pd.DataFrame({'Columna1': [1, 2], 'Columna2': [3, 4]})
    print("Pandas está instalado correctamente.")
except ImportError:
    print("Pandas no está instalado. Por favor, instala usando: pip install pandas")
except:
    print("Pandas está instalado pero no está funcionando adecuadamente.")

NumPy está instalado correctamente.
Pandas está instalado correctamente.


1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [4]:
array_aleatorio1 = np.random.randint(34, 99, size=(4, 3))  # crea un valor aleatorio entre 34 (inclusive) y 99 (exclusivo)
print("Array aleatorio:\n", array_aleatorio1)

Array aleatorio:
 [[37 51 69]
 [86 68 77]
 [77 39 65]
 [86 77 68]]


In [5]:
array_aleatorio1

array([[37, 51, 69],
       [86, 68, 77],
       [77, 39, 65],
       [86, 77, 68]])

In [6]:
print("Número de dimensiones (ndim):", array_aleatorio1.ndim) # 2 dimensiones
print("Forma (shape):", array_aleatorio1.shape) # 2 filas y 4 columnas
print("Tamaño total (size):", array_aleatorio1.size) # número de elementos 
print("Tipo de datos (dtype):", array_aleatorio1.dtype) # tipo de dato

Número de dimensiones (ndim): 2
Forma (shape): (4, 3)
Tamaño total (size): 12
Tipo de datos (dtype): int32


2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

Las listas para crear los arrays son las siguientes

Copy
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [7]:
lista1 = [34,56,71,98, 10]
array1D = np.array(lista1)

In [8]:
lista2 = [[23,45,89, 56], [12,43,82,44]]
array2D = np.array(lista2)

In [9]:
array1D

array([34, 56, 71, 98, 10])

In [10]:
array2D

array([[23, 45, 89, 56],
       [12, 43, 82, 44]])


3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

El primer elemento.

Lo elementos que están en posición impar.

Los cuatro primeros elementos.

Los últimos tres elementos.

Los elementos entre el 4 y el 8 (incluido).

In [17]:
array_arange = np.arange(50)
print(f"Array arange(50):\n{array_arange}\n")

Array arange(50):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]



In [19]:
array_arange[0]

0

In [20]:
array_arange[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [22]:
array_arange[0:4]

array([0, 1, 2, 3])

In [23]:
array_arange[-3:]

array([47, 48, 49])

In [24]:
array_arange[4:9]

array([4, 5, 6, 7, 8])

4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

La primera fila y todas las columnas.

Todas las filas pares.

La primera columna y todas las filas.

In [25]:
array_aleatorio1 = np.random.randint(0, 100, size=(4, 5))  
print("Array aleatorio:\n", array_aleatorio1)

Array aleatorio:
 [[58 15 32 96 52]
 [84 83 90 20 60]
 [ 8 76 70 60 51]
 [35 72 94 33 77]]


In [28]:
array_arange = np.arange(20).reshape(4, 5)
print(f"Array arange(20):\n{array_arange}\n")

Array arange(20):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [29]:
array_arange = np.arange(100).reshape(10, 10)

In [30]:
array_arange

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
array_arange[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
array_arange[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
array_arange[:, ::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [38]:
array_aleatorio1 = np.random.randint(0, 51, size=(4, 5))  
print("Array aleatorio:\n", array_aleatorio1)

Array aleatorio:
 [[30 27 20 49 29]
 [27 33 48 33 17]
 [35 49 40 39 21]
 [ 0 17  7  2 46]]


In [ ]:
mascara = np.where(array_aleatorio1 > 30, < 10